version: '3.1'

services:
  app:
    container_name: mirkomil
    image: mirkomil/accounts
    build: ./
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/account_ms_db
    ports:
      - "8084:8080"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root123
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=account_ms_db